% events = {'name', bot, 'type', 'type_name'}
events1 = { 'a01f',  1,  'Region';
    'a02f',  1,  'Region';
    'a03f',  1,  'Region';
    'a04f',  1,  'Region';
    'a05e',  1,  'Region';
    'a06e',  1,  'Region';
    'a07e',  1,  'Region';
    'a08e',  1,  'Region';
    'b01f',  2,  'Region';
    'b02f',  2,  'Region';
    'b03f',  2,  'Region';
    'b04f',  2,  'Region';
    'b05e',  2,  'Region';
    'b06e',  2,  'Region';
    'b07e',  2,  'Region';
    'b08e',  2,  'Region' };


initial_state = '1';
final_state = '1';

% states = {'name', {'event_name', 'state_name', 'isControllable: c_uc', 'cost';
%                    'event_name', 'state_name', 'isControllable: c_uc', 'cost'}, 'isDone: 0_1'}
states1 = { '1',  { 'b07e',  '2',  'c',  'o';
    'a06e',  '3',  'c',  'o';
    'a01f',  '1',  'uc',  'o' },  1;
    '2',  { 'a06e',  '7',  'c',  'o';
    'a01f',  '2',  'uc',  'o';
    'a08e',  '6',  'c',  'o';
    'b08e',  '1',  'c',  'o';
    'b06e',  '4',  'c',  'o';
    'b02f',  '2',  'uc',  'o' },  1;
    '3',  { 'b07e',  '7',  'c',  'o';
    'a07e',  '10',  'c',  'o';
    'a03f',  '3',  'uc',  'o';
    'a04f',  '3',  'uc',  'o';
    'a05e',  '1',  'c',  'o';
    'b05e',  '8',  'c',  'o' },  1;
    '4',  { 'b07e',  '2',  'c',  'o';
    'a01f',  '4',  'uc',  'o';
    'a08e',  '5',  'c',  'o';
    'b03f',  '4',  'uc',  'o';
    'b04f',  '4',  'uc',  'o' },  1;
    '5',  { 'b07e',  '6',  'c',  'o';
    'b03f',  '5',  'uc',  'o';
    'b04f',  '5',  'uc',  'o';
    'a07e',  '11',  'c',  'o';
    'a05e',  '4',  'c',  'o';
    'b05e',  '12',  'c',  'o' },  1;
    '6',  { 'b06e',  '5',  'c',  'o';
    'b02f',  '6',  'uc',  'o';
    'a05e',  '2',  'c',  'o' },  1;
    '7',  { 'b08e',  '3',  'c',  'o';
    'b02f',  '7',  'uc',  'o';
    'a03f',  '7',  'uc',  'o';
    'a04f',  '7',  'uc',  'o';
    'a05e',  '2',  'c',  'o' },  1;
    '8',  { 'b08e',  '3',  'c',  'o';
    'a07e',  '9',  'c',  'o';
    'a03f',  '8',  'uc',  'o';
    'a04f',  '8',  'uc',  'o';
    'b01f',  '8',  'uc',  'o' },  1;
    '9',  { 'a06e',  '8',  'c',  'o';
    'a08e',  '12',  'c',  'o';
    'b08e',  '10',  'c',  'o';
    'b06e',  '11',  'c',  'o';
    'b01f',  '9',  'uc',  'o';
    'a02f',  '9',  'uc',  'o' },  1;
    '10',  { 'a06e',  '3',  'c',  'o';
    'b05e',  '9',  'c',  'o';
    'a02f',  '10',  'uc',  'o' },  1;
    '11',  { 'a08e',  '5',  'c',  'o';
    'b03f',  '11',  'uc',  'o';
    'b04f',  '11',  'uc',  'o';
    'b05e',  '9',  'c',  'o';
    'a02f',  '11',  'uc',  'o' },  1;
    '12',  { 'b06e',  '5',  'c',  'o';
    'a07e',  '9',  'c',  'o';
    'b01f',  '12',  'uc',  'o' },  1 };

