function event_path = calcEventPathIncr(states,pc,state_path)
% Author: Daniel Burke
% Version: 1.0
% Date: August 10, 2016
% Changelog:
%  1.0: Initial Release
% Current Capability:
%  A quick and useful function that outputs a list of events that connects the
%  path of states generated by Dijkstra.
%  MODIFIED TO HANDLE INCREMENTAL DATA STORAGE
% Input:
%  states = A cell matrix from userdata of all the states and transitions
%  pc = the current element location in the path 
%  path = A cell array of the state numbers that is the optimal path through the
%         FSM
% Output:
%  event_path = A cell array of strings that show what events should occur 
%               between states in the given path

for l = pc:numel(state_path)-1

  cur_state = state_path(l);
  % Next two lines are modified to fit the trans_mat data structure
  next_state_name = num2str(state_path(l+1));
  next_state_index = 1;%strcmp(next_state_name,states{cur_state,2}(:,2));
  % based on chosen path, find the next desired state
  event_path{l} = states{cur_state,2}{next_state_index,1};%{1};
  %disp(states{cur_state,2}{next_state_index,1})

end