function [ event_list ] = createEventFsmList( events,num_fsms )
%CREATEEVENTFSMLIST creates a list of all the events and which FSMs have
%  those events in the second column with the region and task information
%  in the 3rd and 4th column to match the info generated by the gui
%   Coded by Daniel Burke

%Initializes using the first fsm
event_list = events{1}(:,1);

event_list(:,2) = num2cell(1);

for kk = 1:size(event_list)
  if(strcmp(event_list{kk,1}(end),'s'))
    event_list{kk,3} = 'Task';
    event_list{kk,4} = ['tsk' event_list{kk,1}(2:end-1)];
  elseif(strcmp(event_list{kk,1}(end),'f'))
    event_list{kk,3} = 'Region';
    event_list{kk,4} = ['regtsk' event_list{kk,1}(2:end-1)];
  else
    event_list{kk,3} = 'Region';
    event_list{kk,4} = ['reg' event_list{kk,1}(2:end-1)];
  end
end

for i = 2:num_fsms
  % Compares against all of the currently added values
  events_size = size(event_list);
  fsm_events = size(events{i});
  for j = 1:fsm_events
    %Compares to each value in next fsm
    added_yet = false;
    for k = 1:events_size
      if(strcmp(event_list(k,1),events{i}(j,1)))
        %Adds the fsm num to list
        added_yet = true;
        event_list{k,2}(end+1) = i;
        break
      end
    end
    % If not added yet we add to bottom of list
    if(~added_yet)
      event_list(end+1,1) = events{i}(j,1);
      event_list(end,2) = num2cell(i);
      if(strcmp(event_list{end,1}(end),'s'))
        event_list{end,3} = 'Task';
        event_list{end,4} = ['tsk' event_list{end,1}(2:end-1)];
      elseif(strcmp(event_list{end,1}(end),'f'))
        event_list{end,3} = 'Region';
        event_list{end,4} = ['regtsk' event_list{end,1}(2:end-1)];
      else
        event_list{end,3} = 'Region';
        event_list{end,4} = ['reg' event_list{end,1}(2:end-1)];
      end
      
    end
  end  
end  

end

